// Generated by Haxe 4.3.7
(function ($global) { "use strict";
class EReg {
	constructor(r,opt) {
		this.r = new RegExp(r,opt.split("u").join(""));
	}
}
EReg.__name__ = true;
class HxOverrides {
	static cca(s,index) {
		let x = s.charCodeAt(index);
		if(x != x) {
			return undefined;
		}
		return x;
	}
	static substr(s,pos,len) {
		if(len == null) {
			len = s.length;
		} else if(len < 0) {
			if(pos == 0) {
				len = s.length + len;
			} else {
				return "";
			}
		}
		return s.substr(pos,len);
	}
	static now() {
		return Date.now();
	}
}
HxOverrides.__name__ = true;
class Main {
	static main() {
		window.document.addEventListener("DOMContentLoaded",function(_) {
			Main.inputUrl = window.document.getElementById("inputUrl");
			Main.outputUrl = window.document.getElementById("outputUrl");
			Main.inputCount = window.document.getElementById("inputCount");
			Main.outputCount = window.document.getElementById("outputCount");
			Main.clearBtn = window.document.getElementById("clearBtn");
			Main.copyBtn = window.document.getElementById("copyBtn");
			Main.toast = window.document.getElementById("toast");
			Main.inputUrl.addEventListener("input",function(_) {
				Main.processUrls();
			});
			Main.clearBtn.addEventListener("click",function(_) {
				Main.clearAll();
			});
			Main.copyBtn.addEventListener("click",function(_) {
				Main.copyToClipboard();
			});
			Main.processUrls();
		});
	}
	static processUrls() {
		let rawValue = Main.inputUrl.value;
		let cleanedValue = rawValue.replace(Main.HIRAGANA_RE.r,"");
		Main.outputUrl.value = cleanedValue;
		Main.inputCount.textContent = rawValue.length + " 文字";
		Main.outputCount.textContent = cleanedValue.length + " 文字";
		Main.copyBtn.disabled = StringTools.trim(cleanedValue).length == 0;
	}
	static copyToClipboard() {
		if(Main.outputUrl.value == null || Main.outputUrl.value == "") {
			return;
		}
		let text = Main.outputUrl.value;
		let nav = window.navigator;
		let clip = Reflect.field(nav,"clipboard");
		if(clip != null && Object.prototype.hasOwnProperty.call(clip,"writeText")) {
			let promise = Reflect.field(clip,"writeText").apply(clip,[text]);
			if(promise != null && Object.prototype.hasOwnProperty.call(promise,"then")) {
				Reflect.field(promise,"then").apply(promise,[function(_) {
					Main.showToast();
				},function(_) {
					Main.fallbackCopy(text);
				}]);
				return;
			}
		}
		Main.fallbackCopy(text);
	}
	static fallbackCopy(text) {
		Main.outputUrl.select();
		try {
			eval("document.execCommand('copy');");
			window.getSelection().removeAllRanges();
			Main.showToast();
		} catch( _g ) {
			let _g1 = haxe_Exception.caught(_g).unwrap();
			$global.console.error("コピー失敗: " + Std.string(_g1));
			window.alert("コピーに失敗しました。ブラウザの権限を確認してください。");
		}
	}
	static showToast() {
		Main.toast.classList.add("show");
		window.setTimeout(function() {
			Main.toast.classList.remove("show");
		},2000);
	}
	static clearAll() {
		Main.inputUrl.value = "";
		Main.processUrls();
		Main.inputUrl.focus();
	}
}
Main.__name__ = true;
Math.__name__ = true;
class Reflect {
	static field(o,field) {
		try {
			return o[field];
		} catch( _g ) {
			return null;
		}
	}
}
Reflect.__name__ = true;
class Std {
	static string(s) {
		return js_Boot.__string_rec(s,"");
	}
}
Std.__name__ = true;
class StringTools {
	static isSpace(s,pos) {
		let c = HxOverrides.cca(s,pos);
		if(!(c > 8 && c < 14)) {
			return c == 32;
		} else {
			return true;
		}
	}
	static ltrim(s) {
		let l = s.length;
		let r = 0;
		while(r < l && StringTools.isSpace(s,r)) ++r;
		if(r > 0) {
			return HxOverrides.substr(s,r,l - r);
		} else {
			return s;
		}
	}
	static rtrim(s) {
		let l = s.length;
		let r = 0;
		while(r < l && StringTools.isSpace(s,l - r - 1)) ++r;
		if(r > 0) {
			return HxOverrides.substr(s,0,l - r);
		} else {
			return s;
		}
	}
	static trim(s) {
		return StringTools.ltrim(StringTools.rtrim(s));
	}
}
StringTools.__name__ = true;
class haxe_Exception extends Error {
	constructor(message,previous,native) {
		super(message);
		this.message = message;
		this.__previousException = previous;
		this.__nativeException = native != null ? native : this;
	}
	unwrap() {
		return this.__nativeException;
	}
	static caught(value) {
		if(((value) instanceof haxe_Exception)) {
			return value;
		} else if(((value) instanceof Error)) {
			return new haxe_Exception(value.message,null,value);
		} else {
			return new haxe_ValueException(value,null,value);
		}
	}
}
haxe_Exception.__name__ = true;
class haxe_ValueException extends haxe_Exception {
	constructor(value,previous,native) {
		super(String(value),previous,native);
		this.value = value;
	}
	unwrap() {
		return this.value;
	}
}
haxe_ValueException.__name__ = true;
class haxe_iterators_ArrayIterator {
	constructor(array) {
		this.current = 0;
		this.array = array;
	}
	hasNext() {
		return this.current < this.array.length;
	}
	next() {
		return this.array[this.current++];
	}
}
haxe_iterators_ArrayIterator.__name__ = true;
class js_Boot {
	static __string_rec(o,s) {
		if(o == null) {
			return "null";
		}
		if(s.length >= 5) {
			return "<...>";
		}
		let t = typeof(o);
		if(t == "function" && (o.__name__ || o.__ename__)) {
			t = "object";
		}
		switch(t) {
		case "function":
			return "<function>";
		case "object":
			if(((o) instanceof Array)) {
				let str = "[";
				s += "\t";
				let _g = 0;
				let _g1 = o.length;
				while(_g < _g1) {
					let i = _g++;
					str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
				}
				str += "]";
				return str;
			}
			let tostr;
			try {
				tostr = o.toString;
			} catch( _g ) {
				return "???";
			}
			if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
				let s2 = o.toString();
				if(s2 != "[object Object]") {
					return s2;
				}
			}
			let str = "{\n";
			s += "\t";
			let hasp = o.hasOwnProperty != null;
			let k = null;
			for( k in o ) {
			if(hasp && !o.hasOwnProperty(k)) {
				continue;
			}
			if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
				continue;
			}
			if(str.length != 2) {
				str += ", \n";
			}
			str += s + k + " : " + js_Boot.__string_rec(o[k],s);
			}
			s = s.substring(1);
			str += "\n" + s + "}";
			return str;
		case "string":
			return o;
		default:
			return String(o);
		}
	}
}
js_Boot.__name__ = true;
if(typeof(performance) != "undefined" ? typeof(performance.now) == "function" : false) {
	HxOverrides.now = performance.now.bind(performance);
}
{
	String.__name__ = true;
	Array.__name__ = true;
}
js_Boot.__toStr = ({ }).toString;
Main.HIRAGANA_RE = new EReg("[\\u3040-\\u309F]","g");
Main.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
